// utils/data.js
export const data = {
    products: [
        {
        id: '1',
        name: '인두기',
        image: '/images/p1.jpg',
        price: 299,
        countInStock: 10,
        rating: 4.5,
        numReviews: 50,
        description: '고급형 인두기를 구매해보세요',
        },
        {
        id: '2',
        name: '라즈베리파이 풀 키트',
        image: '/images/p2.jpg',
        price: 89.9,
        countInStock: 50,
        rating: 4.0,
        numReviews: 14,
        description: '라즈베리파이4 풀 키트를 저렴한 가격에 구매하세요',
        },
        {
        id: '3',
        name: 'UART to USB',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        rating: 5.0,
        numReviews: 149,
        description: '저렴한 가격에 UART to USB를 구매해보세요',
        },
        {
        id: '4',
        name: '고급형 롱노우즈 빨간색',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        rating: 4.5,
        numReviews: 121,
        description: '믿고 구매할 수 있는 국산 롱노우즈 지금 구매하세요!',
        },
        {
        id: '5',
        name: '블랙앤데커 열풍기/히팅건',
        image: '/images/p5.jpg',
        price: 19.9,
        countInStock: 0,
        rating: 4.5,
        numReviews: 12,
        description: '히팅건을 사용해보세요.',
        },
        {
        id: '6',
        name: '전기릴선, 전선릴 25M',
        image: '/images/p6.jpg',
        price: 250,
        countInStock: 2,
        rating: 3.5,
        numReviews: 54,
        description: '국산 KS인증 전기릴선',
        },
        {
        id: '7',
        name: 'USB C타입 연장케이블',
        image: '/images/p7.jpg',
        price: 2.99,
        countInStock: 15,
        rating: 4.5,
        numReviews: 302,
        description: '0.15M Gen1 고속충전 데이터 연결 연장선입니다',
        },
        {
        id: '8',
        name: '다용도 어댑터',
        image: '/images/p8.jpg',
        price: 32,
        countInStock: 0,
        rating: 4.5,
        numReviews: 92,
        description: 'USB 포트 및 해외 멀티 플러그 어댑터입니다',
        },
    ],
} 